### PR TITLE
Add ApprovePullRequest and MergePullRequest methods 

### PR DESCRIPTION
**Pull request by 4ltieres**
Would be great to have ApprovePullRequest and MergePullRequest methods on this tool.

### CODE REVIEW

**Comment by ae6rt** [comment]
Thank you for your contribution.

**Comment by 4ltieres** [comment]
Hi @ae6rt, do you have idea when will generate a new release version with develop branch?
Let me know if I can help with something.
Tks a lot for stash library.

**Comment by ae6rt** [comment]
Do you mean when can we merge develop to master and tag?  Please do a merge to master locally, build the tests, and if it passes, we can cut a release.  Thanks!

**Comment by 4ltieres** [comment]
Yeah, exactly. I did locally merge from develop to master and all tests passed.

```
asfreitas stash$ make all
go fmt
go vet
go test -v
=== RUN   TestApprovePullRequest
2018/10/12 20:51:12 retry.go:41: retrying...
2018/10/12 20:51:14 retry.go:41: retrying...
2018/10/12 20:51:15 retry.go:41: retrying...
2018/10/12 20:51:17 retry.go:41: retrying...
--- PASS: TestApprovePullRequest (6.01s)
=== RUN   TestGetBranches
--- PASS: TestGetBranches (0.00s)
=== RUN   TestGetBranches500
2018/10/12 20:51:18 retry.go:41: retrying...
2018/10/12 20:51:20 retry.go:41: retrying...
--- PASS: TestGetBranches500 (3.00s)
=== RUN   TestCreateBranchRestriction
--- PASS: TestCreateBranchRestriction (0.00s)
=== RUN   TestCreateBranchRestriction404
--- PASS: TestCreateBranchRestriction404 (0.00s)
=== RUN   TestCreateBranchRestriction401
--- PASS: TestCreateBranchRestriction401 (0.00s)
=== RUN   TestCreatePullRequest
--- PASS: TestCreatePullRequest (0.00s)
=== RUN   TestCreateRepository
--- PASS: TestCreateRepository (0.00s)
=== RUN   TestDeclinePullRequest
2018/10/12 20:51:21 retry.go:41: retrying...
2018/10/12 20:51:23 retry.go:41: retrying...
--- PASS: TestDeclinePullRequest (3.00s)
=== RUN   TestDeleteBranch
--- PASS: TestDeleteBranch (0.00s)
=== RUN   TestDeleteBranchRestriction
--- PASS: TestDeleteBranchRestriction (0.00s)
=== RUN   TestDeleteBranchRestriction404
2018/10/12 20:51:24 retry.go:41: retrying...
2018/10/12 20:51:26 retry.go:41: retrying...
--- PASS: TestDeleteBranchRestriction404 (3.00s)
=== RUN   TestDeleteBranchRestrilction401
2018/10/12 20:51:27 retry.go:41: retrying...
2018/10/12 20:51:29 retry.go:41: retrying...
--- PASS: TestDeleteBranchRestrilction401 (3.00s)
=== RUN   TestGetBranchRestrictions
--- PASS: TestGetBranchRestrictions (0.00s)
=== RUN   TestGetBranchRestrictions404
2018/10/12 20:51:30 retry.go:41: retrying...
2018/10/12 20:51:32 retry.go:41: retrying...
--- PASS: TestGetBranchRestrictions404 (3.00s)
=== RUN   TestGetBranchRestrictions401
2018/10/12 20:51:33 retry.go:41: retrying...
2018/10/12 20:51:35 retry.go:41: retrying...
--- PASS: TestGetBranchRestrictions401 (3.00s)
=== RUN   TestGetCommit
--- PASS: TestGetCommit (0.00s)
=== RUN   TestGetCommit404
2018/10/12 20:51:36 retry.go:41: retrying...
2018/10/12 20:51:38 retry.go:41: retrying...
--- PASS: TestGetCommit404 (3.00s)
=== RUN   TestGetCommit401
2018/10/12 20:51:39 retry.go:41: retrying...
2018/10/12 20:51:41 retry.go:41: retrying...
--- PASS: TestGetCommit401 (3.00s)
=== RUN   TestGetCommit400
2018/10/12 20:51:42 retry.go:41: retrying...
2018/10/12 20:51:44 retry.go:41: retrying...
--- PASS: TestGetCommit400 (3.00s)
=== RUN   TestGetCommits
--- PASS: TestGetCommits (0.00s)
    getcommits_test.go:19: [6782bf94782450a4e6a0d548e4c803692ca38b94]
=== RUN   TestGetCommits404
2018/10/12 20:51:45 retry.go:41: retrying...
2018/10/12 20:51:47 retry.go:41: retrying...
--- PASS: TestGetCommits404 (3.00s)
=== RUN   TestGetCommits401
2018/10/12 20:51:48 retry.go:41: retrying...
2018/10/12 20:51:50 retry.go:41: retrying...
--- PASS: TestGetCommits401 (3.00s)
=== RUN   TestGetCommits400
2018/10/12 20:51:51 retry.go:41: retrying...
2018/10/12 20:51:53 retry.go:41: retrying...
--- PASS: TestGetCommits400 (3.00s)
=== RUN   TestGetRawFile
--- PASS: TestGetRawFile (0.00s)
=== RUN   TestGetRepository
--- PASS: TestGetRepository (0.00s)
=== RUN   TestGetRepository404
2018/10/12 20:51:54 retry.go:41: retrying...
2018/10/12 20:51:56 retry.go:41: retrying...
--- PASS: TestGetRepository404 (3.00s)
=== RUN   TestGetRepository401
2018/10/12 20:51:57 retry.go:41: retrying...
2018/10/12 20:51:59 retry.go:41: retrying...
--- PASS: TestGetRepository401 (3.00s)
=== RUN   TestGetSshUrl
--- PASS: TestGetSshUrl (0.00s)
=== RUN   TestGetSshUrlMissing
--- PASS: TestGetSshUrlMissing (0.00s)
=== RUN   TestHasRepository
--- PASS: TestHasRepository (0.00s)
=== RUN   TestMergePullRequest
2018/10/12 20:52:00 retry.go:41: retrying...
2018/10/12 20:52:02 retry.go:41: retrying...
--- PASS: TestMergePullRequest (3.00s)
=== RUN   TestGetRepositories
--- PASS: TestGetRepositories (0.00s)
=== RUN   TestGetRepositories500
2018/10/12 20:52:03 retry.go:41: retrying...
2018/10/12 20:52:05 retry.go:41: retrying...
--- PASS: TestGetRepositories500 (3.00s)
=== RUN   TestRepositoryNotExists
--- PASS: TestRepositoryNotExists (0.00s)
=== RUN   TestRepositoryNotFound
--- PASS: TestRepositoryNotFound (0.00s)
=== RUN   TestGetTags
--- PASS: TestGetTags (0.00s)
=== RUN   TestGetTagsAnonymous
--- PASS: TestGetTagsAnonymous (0.00s)
=== RUN   TestUpdatePullRequest
--- PASS: TestUpdatePullRequest (0.00s)
PASS
ok  	github.com/4ltieres/stash	54.099s

**Pull request merged**
